#!/usr/bin/bash
# This code write by Ms.nope
clear
echo "Updating..."
sleep 2
cd .. && cd .. && sudo rm -r hacktools && git clone https://github.com/msprogrammer2938/hacktools
echo ""
echo "Finish Updaing!"
echo ""
exit 1
